"""Transformer les mesures en tableaux Markdown, et rien d'autre.

Ce fichier n'a le droit de calculer aucun chiffre. Il lit `comparaison.json` et
`transfert.json`, et les met en forme. C'est délibéré : dès qu'un chiffre est
recopié à la main dans un README, il survit à la mesure qui l'a produit et on
finit par défendre en public un résultat qui n'existe plus dans le code.

Les deux commandes qui produisent les JSON sont les seules sources :

    python -m wiiga.resultats --journees 365
    python -m wiiga.transfert  --journees 365

Puis `python -m wiiga.rapport` réécrit la section chiffrée du README entre les
deux balises. Le reste du README est écrit à la main et n'est jamais touché.
"""

from __future__ import annotations

import json
from pathlib import Path

RACINE = Path(__file__).resolve().parent.parent
COMPARAISON = RACINE / "resultats" / "comparaison.json"
TRANSFERT = RACINE / "resultats" / "transfert.json"
GRAINES = RACINE / "resultats" / "graines.json"
EQUIVALENCE = RACINE / "resultats" / "equivalence.json"
README = RACINE / "README.md"

DEBUT = "<!-- chiffres:début -->"
FIN = "<!-- chiffres:fin -->"

SAISONS = ("sèche chaude", "pluies", "sèche tempérée")


def _fr(x: float, decimales: int = 0) -> str:
    """Un nombre lisible : espace fine pour les milliers, virgule décimale."""
    s = f"{x:,.{decimales}f}".replace(",", " ").replace(".", ",")
    return s


def tableau_principal(d: dict) -> list[str]:
    m = d["mesures"]
    lignes = [
        "| operator | dry hours / day | dry days / 200 | local currency / day "
        "| L diesel / day | kg CO2 / day | tank low point |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for nom, v in m.items():
        gras = "**" if nom.startswith("agent WIIGA (") else ""
        lignes.append(
            f"| {gras}{nom}{gras} | {_fr(v['heures_a_sec_par_jour'], 2)} "
            f"| {v['jours_avec_coupure_sur_200']} | {_fr(v['fcfa_par_jour'])} "
            f"| {_fr(v['litres_gasoil_par_jour'], 1)} "
            f"| {_fr(v['kg_co2_par_jour'], 1)} | {_fr(v['creux_moyen'], 2)} |"
        )
    return lignes


def tableau_saisons(d: dict) -> list[str]:
    m = d["mesures"]
    presentes = [s for s in SAISONS if s in next(iter(m.values()))["heures_a_sec_par_saison"]]
    saison_en = {"sèche chaude": "hot dry", "pluies": "rainy",
                 "sèche tempérée": "mild dry"}
    lignes = [
        "| operator | " + " | ".join(saison_en.get(x, x) for x in presentes) + " |",
        "|---" + "|---:" * len(presentes) + "|",
    ]
    for nom, v in m.items():
        gras = "**" if nom.startswith("agent WIIGA (") else ""
        cases = " | ".join(
            _fr(v["heures_a_sec_par_saison"][s], 2) for s in presentes
        )
        lignes.append(f"| {gras}{nom}{gras} | {cases} |")
    return lignes


def tableau_parole(d: dict) -> list[str]:
    m = d["mesures"]
    lignes = [
        "| operator | warnings / day | accuracy | trust at the end |",
        "|---|---:|---:|---:|",
    ]
    for nom, v in m.items():
        if v["alertes_par_jour"] == 0 and not nom.startswith("agent"):
            continue
        lignes.append(
            f"| {nom} | {_fr(v['alertes_par_jour'], 2)} "
            f"| {_fr(v['justesse_alertes'] * 100)} % "
            f"| {_fr(v['confiance_finale'], 2)} |"
        )
    return lignes


def tableau_transfert(d: dict) -> list[str]:
    lignes = [
        "| city | rainy / hot / mild (days) | agent | rulebook "
        "| difference | warnings / day |",
        "|---|:--:|---:|---:|---:|---:|",
    ]
    for nom, v in d["villes"].items():
        s = v["saisons"]
        saisons = " / ".join(
            str(s.get(k, 0)) for k in ("pluies", "sèche chaude", "sèche tempérée")
        )
        vu = " *(training city)*" if nom == d["entraine_sur"] else ""
        lignes.append(
            f"| {nom}{vu} | {saisons} "
            f"| {_fr(v['agent']['heures_a_sec_par_jour'], 2)} "
            f"| {_fr(v['regle_ecrite']['heures_a_sec_par_jour'], 2)} "
            f"| {_fr(v['ecart_heures_a_sec_pct'])} % "
            f"| {_fr(v['agent']['alertes_par_jour'], 2)} |"
        )
    return lignes


def construire() -> str:
    d = json.loads(COMPARAISON.read_text(encoding="utf-8"))
    r = d["resume"]
    bloc: list[str] = []

    bloc.append(
        f"*{d['journees']} simulated days, one per day of the year, identical seeds for "
        f"every policy. Measured on {d['genere_le'][:10]}, regenerated by "
        f"`python -m wiiga.resultats --journees {d['journees']}`.*"
    )
    bloc += ["", "### What each policy costs the city", ""]
    bloc += tableau_principal(d)

    bloc += ["", "### The same table, season by season - dry hours per day", ""]
    bloc += tableau_saisons(d)
    bloc += [
        "",
        "The annual average hides the point: the hand-written rules give way in the",
        "hot dry season, which is exactly when the city is thirstiest.",
    ]

    bloc += ["", "### Speech: what the agent tells the city, and whether it is believed", ""]
    bloc += tableau_parole(d)

    ecarts = [
        ("what the utility runs today", r["vs_pratique_actuelle"]),
        ("the hand-written rulebook", r["vs_regle_ecrite"]),
        ("itself, with the warning switched off", r["vs_lui_meme_sans_la_parole"]),
    ]
    bloc += ["", "### At a glance", ""]
    for titre, e in ecarts:
        morceaux = [f"{_fr(e['heures_a_sec_pct'])} % fewer dry hours"]
        if "cout_pct" in e:
            morceaux.append(f"{_fr(e['cout_pct'])} % cheaper to run")
        if "co2_pct" in e:
            morceaux.append(f"{_fr(e['co2_pct'])} % less CO2")
        bloc.append(f"- **against {titre}**: " + ", ".join(morceaux))

    if GRAINES.exists():
        g = json.loads(GRAINES.read_text(encoding="utf-8"))
        e = g["ecart_a_la_regle_pct"]
        bloc += [
            "",
            "### Does the result survive its own variance",
            "",
            "*PPO is stochastic. A single lucky run proves nothing, so here are "
            "three complete trainings on three seeds, evaluated on the same days "
            "against the same rules.*",
            "",
            "| training seed | dry hours / day | warnings / day | warning accuracy |",
            "|---|---:|---:|---:|",
        ]
        for nom, m in g["graines"].items():
            bloc.append(
                f"| {nom.replace('graine_', 'seed ')} "
                f"| {_fr(m['heures_a_sec_par_jour'], 2)} "
                f"| {_fr(m['alertes_par_jour'], 2)} "
                f"| {_fr(m['justesse_alertes'] * 100)} % |"
            )
        regle = g["regles"]["prévoyant (règle écrite)"]
        bloc.append(
            f"| **the rulebook they all beat** "
            f"| **{_fr(regle['heures_a_sec_par_jour'], 2)}** | 0 | - |"
        )
        verdict = (
            "All three seeds beat the hand-written rulebook"
            if g["toutes_les_graines_battent_la_regle"]
            else "**At least one seed loses to the rulebook**, and that is said here"
        )
        bloc += [
            "",
            f"{verdict}, by **{_fr(e['moyenne'])} %** on average and "
            f"between **{_fr(e['min'])} %** and **{_fr(e['max'])} %** depending on the "
            "seed. The worst of the three is the number to plan with.",
        ]

    if EQUIVALENCE.exists():
        q = json.loads(EQUIVALENCE.read_text(encoding="utf-8"))
        bloc += ["", "### What it replaces in concrete", ""]
        if q.get("capacite_equivalente"):
            bloc.append(
                f"The simulator is a digital twin, so it answers capital questions. "
                f"The hand-written rulebook only matches the agent at "
                f"**{q['capacite_equivalente']:.2f}x storage** - "
                f"**{_fr(q['m3_de_stockage_evites'])} m3** of new tank on the "
                f"{_fr(q['capacite_actuelle_m3'])} m3 that exist, a "
                f"**{_fr((q['capacite_equivalente'] - 1) * 100)} % expansion**. "
                f"That is what the agent is worth in concrete, and it costs nothing "
                f"to pour."
            )
            if q.get("carburant_equivalent"):
                bloc.append(
                    f"\nBuying the same result with fuel instead takes "
                    f"**{q['carburant_equivalent']:.2f}x the daily generator budget** - "
                    f"more emissions, every day, for as long as the station runs."
                )
        else:
            bloc.append(
                "Even at the largest capacity tested, the rulebook does not catch "
                "the agent. The gap is not a storage problem."
            )

    if TRANSFERT.exists():
        t = json.loads(TRANSFERT.read_text(encoding="utf-8"))
        bloc += [
            "",
            "### And in a city it has never seen",
            "",
            f"*The weights trained on {t['entraine_sur']}, replayed unchanged. Nothing is "
            "retrained: the climatology is swapped, and nothing else.*",
            "",
        ]
        bloc += tableau_transfert(t)
        gagnees = sum(1 for v in t["villes"].values() if v["agent_bat_la_regle"])
        bloc += [
            "",
            f"The agent beats the rulebook in **{gagnees} of {len(t['villes'])}** "
            "of these cities, with nothing retrained. It does not win everywhere, "
            "and the pattern is worth more than a clean sweep would be: **its "
            "advantage tracks how hard the city is.** Where the rulebook already "
            "keeps taps running - Sydney, Lima - there is nothing left to win. "
            "Where the problem bites, the gap opens. A tool that helps most "
            "exactly where the need is greatest is the tool you want.",
        ]

    return "\n".join(bloc)


def main() -> None:
    bloc = construire()
    if not README.exists():
        print(bloc)
        raise SystemExit(
            f"\n({README.name} n'existe pas encore - bloc affiché plutôt qu'inséré)"
        )

    texte = README.read_text(encoding="utf-8")
    if DEBUT not in texte or FIN not in texte:
        print(bloc)
        raise SystemExit(f"\n(balises {DEBUT} / {FIN} absentes du README)")

    avant = texte.split(DEBUT)[0]
    apres = texte.split(FIN)[1]
    README.write_text(f"{avant}{DEBUT}\n\n{bloc}\n\n{FIN}{apres}", encoding="utf-8")
    print(f"section chiffrée réécrite dans {README.name}")


if __name__ == "__main__":
    main()
